name: 'diff-coverage'
description: 'Checks that the added and modified lines are covered by unit tests'
inputs:
  repoDirectory:
    description: 'The directory where the tests were run'
    required: false
    default: ${{ github.workspace }}
  include:
    description: 'JSON array. Only process paths that match a regular expression in `include`. By default includes all.'
    required: false
    default: '[""]'
  ignore:
    description: 'JSON array. Do not process paths that match a regular expression in `ignore`. By default ignores none.'
    required: false
    default: '[]'
runs:
  using: 'node12'
  main: 'dist/index.js'
